name: Deploy

on:
  push:
  
  workflow_dispatch:    

env:
  LOCATION: 'eastus'
  RESOURCE_GROUP_NAME: 'rg-app-service-php-demo'
  FILESHARE_NAME: 'filephpdisk'
  AZURE_WEBAPP_PACKAGE_PATH: './src'  

jobs:

  create-azure-resources:

    runs-on: ubuntu-latest

    outputs:
      webAppName: ${{ steps.armDeployment.outputs.webName }}
      webNodeName: ${{ steps.armDeployment.outputs.webNodeName }}

    steps:

      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create -n ${{ env.RESOURCE_GROUP_NAME }} -l ${{ env.LOCATION }}

      - name: Deploy Azure Resources
        id: armDeployment
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ./bicep/main.bicep
          parameters: location=${{ env.LOCATION }} fileShareName=${{ env.FILESHARE_NAME }}   
          
      - name: output web app name
        run: |
          echo ${{ steps.armDeployment.outputs.webName }}
  
  build-and-deploy-php-app:
    
    needs: create-azure-resources

    runs-on: ubuntu-latest
    
    env:
      WEBAPP_PACKAGE_DIR: 'src'
    
    steps:

      - uses: actions/checkout@master

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ needs.create-azure-resources.outputs.webAppName }}
          package: ${{ env.WEBAPP_PACKAGE_DIR }}
              
  build-and-deloy-node-app:
    
    needs: create-azure-resources

    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_PACKAGE_PATH: './nodeapp'
      NODE_VERSION: '14.x'

    steps:

      - uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install
        run: |
          npm install

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ needs.create-azure-resources.outputs.webNodeName }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}                


          
