name: Deploy

on:
  push:
  
  workflow_dispatch:    

env:
  LOCATION: 'eastus'
  RESOURCE_GROUP_NAME: 'rg-app-service-php-demo'
  FILESHARE_NAME: 'filephpdisk'
  AZURE_WEBAPP_PACKAGE_PATH: './src'

jobs:

  create-azure-resources:

    runs-on: ubuntu-latest

    outputs:
      webAppName: ${{ steps.armDeployment.outputs.webName }}

    steps:

      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create -n ${{ env.RESOURCE_GROUP_NAME }} -l ${{ env.LOCATION }}

      - name: Deploy Azure Resources
        id: armDeployment
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ./bicep/main.bicep
          parameters: location=${{ env.LOCATION }} fileShareName=${{ env.FILESHARE_NAME }}   
          
      - name: output web app name
        run: |
          echo ${{ steps.armDeployment.outputs.webName }}
  
  build-and-deploy:
    
    needs: create-azure-resources

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ needs.create-azure-resources.outputs.webAppName }}
              